services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: artline
      POSTGRES_PASSWORD: artline
      POSTGRES_DB: artline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
