// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateCreativeProjectInput struct {
	Title          string                      `json:"title"`
	Description    *string                     `json:"description,omitempty"`
	StartYear      int                         `json:"startYear"`
	StartMonth     int                         `json:"startMonth"`
	Lyrics         *string                     `json:"lyrics,omitempty"`
	CreationMethod *string                     `json:"creationMethod,omitempty"`
	Links          []*CreativeProjectLinkInput `json:"links,omitempty"`
}

type CreativeProject struct {
	ID             string                 `json:"id"`
	Title          string                 `json:"title"`
	Description    *string                `json:"description,omitempty"`
	StartYear      int                    `json:"startYear"`
	StartMonth     int                    `json:"startMonth"`
	Lyrics         *string                `json:"lyrics,omitempty"`
	CreationMethod *string                `json:"creationMethod,omitempty"`
	Links          []*CreativeProjectLink `json:"links"`
	CreatedAt      string                 `json:"createdAt"`
	UpdatedAt      string                 `json:"updatedAt"`
}

type CreativeProjectLink struct {
	ID        string                      `json:"id"`
	Platform  CreativeProjectLinkPlatform `json:"platform"`
	URL       string                      `json:"url"`
	Label     *string                     `json:"label,omitempty"`
	SortOrder int                         `json:"sortOrder"`
}

type CreativeProjectLinkInput struct {
	Platform  CreativeProjectLinkPlatform `json:"platform"`
	URL       string                      `json:"url"`
	Label     *string                     `json:"label,omitempty"`
	SortOrder *int                        `json:"sortOrder,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateCreativeProjectInput struct {
	Title          *string                     `json:"title,omitempty"`
	Description    *string                     `json:"description,omitempty"`
	StartYear      *int                        `json:"startYear,omitempty"`
	StartMonth     *int                        `json:"startMonth,omitempty"`
	Lyrics         *string                     `json:"lyrics,omitempty"`
	CreationMethod *string                     `json:"creationMethod,omitempty"`
	Links          []*CreativeProjectLinkInput `json:"links,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	DisplayName *string `json:"displayName,omitempty"`
}

type CreativeProjectLinkPlatform string

const (
	CreativeProjectLinkPlatformYoutube        CreativeProjectLinkPlatform = "YOUTUBE"
	CreativeProjectLinkPlatformSpotify        CreativeProjectLinkPlatform = "SPOTIFY"
	CreativeProjectLinkPlatformSoundcloud     CreativeProjectLinkPlatform = "SOUNDCLOUD"
	CreativeProjectLinkPlatformInstagramReels CreativeProjectLinkPlatform = "INSTAGRAM_REELS"
	CreativeProjectLinkPlatformTiktok         CreativeProjectLinkPlatform = "TIKTOK"
	CreativeProjectLinkPlatformWebsite        CreativeProjectLinkPlatform = "WEBSITE"
	CreativeProjectLinkPlatformOther          CreativeProjectLinkPlatform = "OTHER"
)

var AllCreativeProjectLinkPlatform = []CreativeProjectLinkPlatform{
	CreativeProjectLinkPlatformYoutube,
	CreativeProjectLinkPlatformSpotify,
	CreativeProjectLinkPlatformSoundcloud,
	CreativeProjectLinkPlatformInstagramReels,
	CreativeProjectLinkPlatformTiktok,
	CreativeProjectLinkPlatformWebsite,
	CreativeProjectLinkPlatformOther,
}

func (e CreativeProjectLinkPlatform) IsValid() bool {
	switch e {
	case CreativeProjectLinkPlatformYoutube, CreativeProjectLinkPlatformSpotify, CreativeProjectLinkPlatformSoundcloud, CreativeProjectLinkPlatformInstagramReels, CreativeProjectLinkPlatformTiktok, CreativeProjectLinkPlatformWebsite, CreativeProjectLinkPlatformOther:
		return true
	}
	return false
}

func (e CreativeProjectLinkPlatform) String() string {
	return string(e)
}

func (e *CreativeProjectLinkPlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CreativeProjectLinkPlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CreativeProjectLinkPlatform", str)
	}
	return nil
}

func (e CreativeProjectLinkPlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CreativeProjectLinkPlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CreativeProjectLinkPlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
