package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/google/uuid"

	"github.com/donamo/artline-backend/internal/auth"
	dbsqlc "github.com/donamo/artline-backend/internal/db"
	"github.com/donamo/artline-backend/internal/graph/model"
)

var errUnauthorized = errors.New("unauthorized")
var errNotFound = errors.New("not found")

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, nil
	}
	m := &model.User{
		ID:    user.ID.String(),
		Email: user.Email,
	}
	if user.DisplayName.Valid {
		m.DisplayName = &user.DisplayName.String
	}
	return m, nil
}

// MyCreativeProjects is the resolver for the myCreativeProjects field.
func (r *queryResolver) MyCreativeProjects(ctx context.Context) ([]*model.CreativeProject, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errUnauthorized
	}

	projects, err := r.queries.ListCreativeProjectsByOwner(ctx, user.ID)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}

	result := make([]*model.CreativeProject, 0, len(projects))
	for _, p := range projects {
		links, err := r.queries.ListProjectLinks(ctx, p.ID)
		if err != nil {
			return nil, fmt.Errorf("list links: %w", err)
		}
		result = append(result, toModelProject(p, links))
	}
	return result, nil
}

// CreativeProject is the resolver for the creativeProject field.
func (r *queryResolver) CreativeProject(ctx context.Context, id string) (*model.CreativeProject, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errUnauthorized
	}

	projectID, err := uuid.Parse(id)
	if err != nil {
		return nil, errNotFound
	}

	p, err := r.queries.GetCreativeProject(ctx, projectID)
	if err == sql.ErrNoRows {
		return nil, errNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	if p.OwnerUserID != user.ID {
		return nil, errNotFound
	}

	links, err := r.queries.ListProjectLinks(ctx, p.ID)
	if err != nil {
		return nil, fmt.Errorf("list links: %w", err)
	}
	return toModelProject(p, links), nil
}

// CreateCreativeProject is the resolver for the createCreativeProject field.
func (r *mutationResolver) CreateCreativeProject(ctx context.Context, input model.CreateCreativeProjectInput) (*model.CreativeProject, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errUnauthorized
	}

	if err := validateCreateInput(input); err != nil {
		return nil, err
	}

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	q := dbsqlc.New(tx)

	p, err := q.CreateCreativeProject(ctx, dbsqlc.CreateCreativeProjectParams{
		OwnerUserID:    user.ID,
		Title:          input.Title,
		Description:    nullStr(input.Description),
		StartYear:      int32(input.StartYear),
		StartMonth:     int32(input.StartMonth),
		Lyrics:         nullStr(input.Lyrics),
		CreationMethod: nullStr(input.CreationMethod),
	})
	if err != nil {
		return nil, fmt.Errorf("create project: %w", err)
	}

	links, err := insertLinks(ctx, q, p.ID, input.Links)
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}
	return toModelProject(p, links), nil
}

// UpdateCreativeProject is the resolver for the updateCreativeProject field.
func (r *mutationResolver) UpdateCreativeProject(ctx context.Context, id string, input model.UpdateCreativeProjectInput) (*model.CreativeProject, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errUnauthorized
	}

	projectID, err := uuid.Parse(id)
	if err != nil {
		return nil, errNotFound
	}

	existing, err := r.queries.GetCreativeProject(ctx, projectID)
	if err == sql.ErrNoRows {
		return nil, errNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	if existing.OwnerUserID != user.ID {
		return nil, errNotFound
	}

	if err := validateUpdateInput(input); err != nil {
		return nil, err
	}

	// merge: nil input field → keep existing value
	params := dbsqlc.UpdateCreativeProjectParams{
		ID:             projectID,
		Title:          existing.Title,
		Description:    existing.Description,
		StartYear:      existing.StartYear,
		StartMonth:     existing.StartMonth,
		Lyrics:         existing.Lyrics,
		CreationMethod: existing.CreationMethod,
	}
	if input.Title != nil {
		params.Title = *input.Title
	}
	if input.Description != nil {
		params.Description = nullStr(input.Description)
	}
	if input.StartYear != nil {
		params.StartYear = int32(*input.StartYear)
	}
	if input.StartMonth != nil {
		params.StartMonth = int32(*input.StartMonth)
	}
	if input.Lyrics != nil {
		params.Lyrics = nullStr(input.Lyrics)
	}
	if input.CreationMethod != nil {
		params.CreationMethod = nullStr(input.CreationMethod)
	}

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	q := dbsqlc.New(tx)

	p, err := q.UpdateCreativeProject(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("update project: %w", err)
	}

	var links []dbsqlc.CreativeProjectLink
	if input.Links != nil {
		if err := q.DeleteProjectLinks(ctx, p.ID); err != nil {
			return nil, fmt.Errorf("delete links: %w", err)
		}
		links, err = insertLinks(ctx, q, p.ID, input.Links)
		if err != nil {
			return nil, err
		}
	} else {
		links, err = q.ListProjectLinks(ctx, p.ID)
		if err != nil {
			return nil, fmt.Errorf("list links: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}
	return toModelProject(p, links), nil
}

// DeleteCreativeProject is the resolver for the deleteCreativeProject field.
func (r *mutationResolver) DeleteCreativeProject(ctx context.Context, id string) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, errUnauthorized
	}

	projectID, err := uuid.Parse(id)
	if err != nil {
		return false, errNotFound
	}

	p, err := r.queries.GetCreativeProject(ctx, projectID)
	if err == sql.ErrNoRows {
		return false, errNotFound
	}
	if err != nil {
		return false, fmt.Errorf("get project: %w", err)
	}
	if p.OwnerUserID != user.ID {
		return false, errNotFound
	}

	if err := r.queries.DeleteCreativeProject(ctx, projectID); err != nil {
		return false, fmt.Errorf("delete project: %w", err)
	}
	return true, nil
}

func insertLinks(ctx context.Context, q *dbsqlc.Queries, projectID uuid.UUID, inputs []*model.CreativeProjectLinkInput) ([]dbsqlc.CreativeProjectLink, error) {
	links := make([]dbsqlc.CreativeProjectLink, 0, len(inputs))
	for i, li := range inputs {
		sortOrder := int32(i)
		if li.SortOrder != nil {
			sortOrder = int32(*li.SortOrder)
		}
		l, err := q.CreateProjectLink(ctx, dbsqlc.CreateProjectLinkParams{
			ProjectID: projectID,
			Platform:  string(li.Platform),
			Url:       li.URL,
			Label:     nullStr(li.Label),
			SortOrder: sortOrder,
		})
		if err != nil {
			return nil, fmt.Errorf("create link: %w", err)
		}
		links = append(links, l)
	}
	return links, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
