// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProjectLink = `-- name: CreateProjectLink :one
insert into creative_project_links (project_id, platform, url, label, sort_order)
values ($1, $2, $3, $4, $5)
returning id, project_id, platform, url, label, sort_order, created_at, updated_at
`

type CreateProjectLinkParams struct {
	ProjectID uuid.UUID      `db:"project_id" json:"project_id"`
	Platform  string         `db:"platform" json:"platform"`
	Url       string         `db:"url" json:"url"`
	Label     sql.NullString `db:"label" json:"label"`
	SortOrder int32          `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateProjectLink(ctx context.Context, arg CreateProjectLinkParams) (CreativeProjectLink, error) {
	row := q.db.QueryRowContext(ctx, createProjectLink,
		arg.ProjectID,
		arg.Platform,
		arg.Url,
		arg.Label,
		arg.SortOrder,
	)
	var i CreativeProjectLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Url,
		&i.Label,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectLinks = `-- name: DeleteProjectLinks :exec
delete from creative_project_links where project_id = $1
`

func (q *Queries) DeleteProjectLinks(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectLinks, projectID)
	return err
}

const listProjectLinks = `-- name: ListProjectLinks :many
select id, project_id, platform, url, label, sort_order, created_at, updated_at from creative_project_links
where project_id = $1
order by sort_order asc, created_at asc
`

func (q *Queries) ListProjectLinks(ctx context.Context, projectID uuid.UUID) ([]CreativeProjectLink, error) {
	rows, err := q.db.QueryContext(ctx, listProjectLinks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreativeProjectLink
	for rows.Next() {
		var i CreativeProjectLink
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Url,
			&i.Label,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
