// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CreativeProject struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	OwnerUserID    uuid.UUID      `db:"owner_user_id" json:"owner_user_id"`
	Title          string         `db:"title" json:"title"`
	Description    sql.NullString `db:"description" json:"description"`
	StartYear      int32          `db:"start_year" json:"start_year"`
	StartMonth     int32          `db:"start_month" json:"start_month"`
	Lyrics         sql.NullString `db:"lyrics" json:"lyrics"`
	CreationMethod sql.NullString `db:"creation_method" json:"creation_method"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
}

type CreativeProjectLink struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	ProjectID uuid.UUID      `db:"project_id" json:"project_id"`
	Platform  string         `db:"platform" json:"platform"`
	Url       string         `db:"url" json:"url"`
	Label     sql.NullString `db:"label" json:"label"`
	SortOrder int32          `db:"sort_order" json:"sort_order"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	GoogleSubject string         `db:"google_subject" json:"google_subject"`
	Email         string         `db:"email" json:"email"`
	DisplayName   sql.NullString `db:"display_name" json:"display_name"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
}
