// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCreativeProject = `-- name: CreateCreativeProject :one
insert into creative_projects (owner_user_id, title, description, start_year, start_month, lyrics, creation_method)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, owner_user_id, title, description, start_year, start_month, lyrics, creation_method, created_at, updated_at
`

type CreateCreativeProjectParams struct {
	OwnerUserID    uuid.UUID      `db:"owner_user_id" json:"owner_user_id"`
	Title          string         `db:"title" json:"title"`
	Description    sql.NullString `db:"description" json:"description"`
	StartYear      int32          `db:"start_year" json:"start_year"`
	StartMonth     int32          `db:"start_month" json:"start_month"`
	Lyrics         sql.NullString `db:"lyrics" json:"lyrics"`
	CreationMethod sql.NullString `db:"creation_method" json:"creation_method"`
}

func (q *Queries) CreateCreativeProject(ctx context.Context, arg CreateCreativeProjectParams) (CreativeProject, error) {
	row := q.db.QueryRowContext(ctx, createCreativeProject,
		arg.OwnerUserID,
		arg.Title,
		arg.Description,
		arg.StartYear,
		arg.StartMonth,
		arg.Lyrics,
		arg.CreationMethod,
	)
	var i CreativeProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.StartYear,
		&i.StartMonth,
		&i.Lyrics,
		&i.CreationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCreativeProject = `-- name: DeleteCreativeProject :exec
delete from creative_projects where id = $1
`

func (q *Queries) DeleteCreativeProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCreativeProject, id)
	return err
}

const getCreativeProject = `-- name: GetCreativeProject :one
select id, owner_user_id, title, description, start_year, start_month, lyrics, creation_method, created_at, updated_at from creative_projects where id = $1
`

func (q *Queries) GetCreativeProject(ctx context.Context, id uuid.UUID) (CreativeProject, error) {
	row := q.db.QueryRowContext(ctx, getCreativeProject, id)
	var i CreativeProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.StartYear,
		&i.StartMonth,
		&i.Lyrics,
		&i.CreationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreativeProjectsByOwner = `-- name: ListCreativeProjectsByOwner :many
select id, owner_user_id, title, description, start_year, start_month, lyrics, creation_method, created_at, updated_at from creative_projects
where owner_user_id = $1
order by start_year desc, start_month desc, created_at desc
`

func (q *Queries) ListCreativeProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]CreativeProject, error) {
	rows, err := q.db.QueryContext(ctx, listCreativeProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreativeProject
	for rows.Next() {
		var i CreativeProject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.StartYear,
			&i.StartMonth,
			&i.Lyrics,
			&i.CreationMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreativeProject = `-- name: UpdateCreativeProject :one
update creative_projects set
  title = $2,
  description = $3,
  start_year = $4,
  start_month = $5,
  lyrics = $6,
  creation_method = $7,
  updated_at = now()
where id = $1
returning id, owner_user_id, title, description, start_year, start_month, lyrics, creation_method, created_at, updated_at
`

type UpdateCreativeProjectParams struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Title          string         `db:"title" json:"title"`
	Description    sql.NullString `db:"description" json:"description"`
	StartYear      int32          `db:"start_year" json:"start_year"`
	StartMonth     int32          `db:"start_month" json:"start_month"`
	Lyrics         sql.NullString `db:"lyrics" json:"lyrics"`
	CreationMethod sql.NullString `db:"creation_method" json:"creation_method"`
}

func (q *Queries) UpdateCreativeProject(ctx context.Context, arg UpdateCreativeProjectParams) (CreativeProject, error) {
	row := q.db.QueryRowContext(ctx, updateCreativeProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartYear,
		arg.StartMonth,
		arg.Lyrics,
		arg.CreationMethod,
	)
	var i CreativeProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.StartYear,
		&i.StartMonth,
		&i.Lyrics,
		&i.CreationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
