// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByGoogleSubject = `-- name: GetUserByGoogleSubject :one
select id, google_subject, email, display_name, created_at, updated_at from users where google_subject = $1
`

func (q *Queries) GetUserByGoogleSubject(ctx context.Context, googleSubject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleSubject, googleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, google_subject, email, display_name, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
insert into users (google_subject, email, display_name, updated_at)
values ($1, $2, $3, now())
on conflict (google_subject)
do update set
  email = excluded.email,
  display_name = excluded.display_name,
  updated_at = now()
returning id, google_subject, email, display_name, created_at, updated_at
`

type UpsertUserParams struct {
	GoogleSubject string         `db:"google_subject" json:"google_subject"`
	Email         string         `db:"email" json:"email"`
	DisplayName   sql.NullString `db:"display_name" json:"display_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.GoogleSubject, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
